producao/chamados/urls.py
from django.urls import path

from .views import ChamadosCreate

from .views import ChamadosUpdate
from .views import ChamadosDelete
from .views import ChamadosList
from .views import solicitar_chamado
from .views import reverter_status
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('solicitar/chamado/', ChamadosCreate.as_view(), name='chamado'),

    path('chamados/edicao/<int:pk>', ChamadosUpdate.as_view(), name='chamados-edição'),

    path('chamados/excluir/<int:pk>', ChamadosDelete.as_view(), name='chamados-excluir'),

    path('chamados/listar/', ChamadosList.as_view(), name='listar-chamados'),

    path('solicitar_chamado/', solicitar_chamado, name='solicitar_chamado'),

    path('chamados/reverter-status/<int:pk>/', reverter_status, name='reverter-status'),  # Nova rota
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

producao/menu/urls.py
from django.contrib import admin
from django.urls import path
from .views import IndexView
from . import views

urlpatterns = [
    path('menu/', IndexView.as_view(), name='menu'),
    path('error/', views.my_view, name='error'),
]

producao/producao/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('', include('menu.urls')),
    path('', include('chamados.urls')),
]

producao/chamados/models.py
from django.db import models
from django.utils import timezone

class Chamados(models.Model):
    email = models.EmailField(max_length=254, verbose_name="E-mail")
    nome = models.CharField(max_length=150, verbose_name="Nome")

    GENDER_CHOICES = (
        ('B', 'DIREÇÃO'),
        ('C', 'TECNOLOGIA'),
        ('D', 'LOGISTICA'),
        ('E', 'FATURAMENTO'),
        ('F', 'MANUTENÇÃO'),
    )

    departamento = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Departamento")


    descricao = models.TextField(max_length=500, verbose_name="Descrição")
    GENDER_CHOICES = (
        ('M', 'Pendente'),
        ('P', 'Concluído'),
    )

    status = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Status", default='M')
    data = models.DateTimeField(verbose_name="Data/Hora", default=timezone.now, editable="false")
    anexo = models.FileField(upload_to='anexos/', blank=True, null=True, verbose_name="false")

    def __str__(self):
        return f"{self.nome}"

producao/chamados/forms.py
from django import forms
from .models import Chamados

class ChamadoForm(forms.ModelForm):
    class Meta:
        model = Chamados
        fields = ['nome', 'email', 'descricao', 'departamento', 'status', 'data', 'anexo']
        widgets = {
            'data': forms.HiddenInput(),
            'status': forms.HiddenInput(),
        }

    anexo = forms.FileField(required=False, label='Anexo')

producao/chamados/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from .models import Chamados
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import ChamadoForm
from django.conf import settings
import mimetypes
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404, redirect


class ChamadosCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('error')
    model = Chamados
    fields = ['nome', 'email', 'descricao', 'departamento', 'status', 'data', 'anexo']  # Campo 'status' adicionado
    template_name = 'chamado.html'
    success_url = reverse_lazy('listar-chamados')


class ChamadosUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('error')
    model = Chamados
    fields = ['nome', 'email', 'descricao', 'departamento', 'status', 'data', 'anexo']
    template_name = 'chamado.html'
    success_url = reverse_lazy('listar-chamados')


class ChamadosDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('error')
    model = Chamados
    template_name = 'chamado-excluir.html'
    success_url = reverse_lazy('listar-chamados')


class ChamadosList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('error')
    model = Chamados
    template_name = 'lista/chamados-list.html'

def reverter_status(request, pk):
    chamado = get_object_or_404(Chamados, pk=pk)
    # Reverter o status
    chamado.status = 'P' if chamado.status == 'M' else 'M'
    chamado.save()
    return redirect('listar-chamados')    


def solicitar_chamado(request):
    if request.method == 'POST':
        form = ChamadoForm(request.POST, request.FILES)
        if form.is_valid():
            chamado = form.save()

            # Criar mensagem para o administrador
            mensagem_administrador = f"""
            Novo Chamado Solicitado

            Detalhes do chamado:
            Nome: {chamado.nome}
            Email: {chamado.email}
            Departamento: {chamado.departamento}
            Descrição: {chamado.descricao}
            Status: {chamado.status}
            Data: {chamado.data}
            """

            email_administrador = EmailMessage(
                'Novo Chamado Solicitado',
                mensagem_administrador,
                settings.EMAIL_HOST_USER,
                ['aprendiz.bi@viadupla.com'],
            )

            # Anexar arquivo se existir
            if chamado.anexo:
                # Obter o tipo MIME do arquivo
                content_type, encoding = mimetypes.guess_type(chamado.anexo.name)
                content_type = content_type or 'application/octet-stream'
                email_administrador.attach(chamado.anexo.name, chamado.anexo.read(), content_type)

            email_administrador.send(fail_silently=False)

            # Criar mensagem para o usuário
            mensagem_usuario = f"""
            Olá {chamado.nome},

            Recebemos sua solicitação de chamado. Aqui estão os detalhes:

            Nome: {chamado.nome}
            Email: {chamado.email}
            Departamento: {chamado.departamento}
            Descrição: {chamado.descricao}
            Status: {chamado.status}
            Data: {chamado.data}

            Aguarde até receber uma resposta!

            Atenciosamente:
            Via Dupla Transportes
            """

            email_usuario = EmailMessage(
                'Confirmação de Solicitação de Chamado',
                mensagem_usuario,
                settings.EMAIL_HOST_USER,
                [chamado.email],
            )

            # Anexar arquivo se existir
            if chamado.anexo:
                # Obter o tipo MIME do arquivo
                content_type, encoding = mimetypes.guess_type(chamado.anexo.name)
                content_type = content_type or 'application/octet-stream'
                email_usuario.attach(chamado.anexo.name, chamado.anexo.read(), content_type)

            email_usuario.send(fail_silently=False)

            return redirect('listar-chamados')
    else:
        form = ChamadoForm()

    return render(request, 'chamado.html', {'form': form})

producao/chamados/templates/lista/chamados-list.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Listagem dos chamados</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/chamado-list.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.7.2/font/bootstrap-icons.min.css">
</head>
<style>
    .header-text {
        font-family: Arial, sans-serif; /* Fonte Arial */
        font-size: 38px; /* Tamanho do texto 25px */
        text-align: center; /* Centralizar texto */
        font-weight: 600;
        color: #F2B72F;
        padding: 0px 20px;
        z-index: 999;
        margin-top: 30px;
        margin-bottom: -50px;
    }
</style>
<body>

    <a href="{% url 'menu' %}">
        <button class="back-button" onclick="window.history.back();">
            <i class="bi bi-arrow-left-circle-fill"></i>
        </button>
    </a>

    <img class="footer-image" src="{% static 'img/rodapépreto.jpg' %}">
    <img class="image1" src="{% static 'img/linhadocabeçalho.jpg' %}">
    <a href="{% url 'menu' %}">
        <img class="image3" src="{% static 'img/logoVD_FundoEscuro.png' %}">
    </a>
<div class="container">
    <table class="table table-dark table-striped">
        <header class="container header-text">Chamados</header>
        <thead>
        <tr>
            <th>Status</th>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Descrição</th>
            <th>Departamento</th>
            <th>Data/Hora</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        {% for chamado in object_list %}
        <tr>
            <td>{{ chamado.get_status_display }}</td>
            <td>{{ chamado.nome }}</td>
            <td>{{ chamado.email }}</td>
            <td>{{ chamado.descricao }}</td>
            <td>{{ chamado.get_departamento_display }}</td>
            <td>{{ chamado.data }}</td>
            <td>
                <a href="{% url 'chamados-edição' chamado.pk %}" class="btn btn-warning btn-sm" title="Editar">Editar</a>
                <a href="{% url 'chamados-excluir' chamado.pk %}" class="btn btn-warning btn-sm" title="Excluir">Excluir</a>
                <a href="{% url 'reverter-status' chamado.pk %}" class="btn btn-warning btn-sm" title="Reverter Status">Status</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td class="sticky cell-id" colspan="27">Nenhum campo registrado</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>