backup/carretas/urls.py
from django.urls import path

from .views import CarretasCreate
from .views import CarretasUpdate
from .views import CarretasDelete
from .views import CarretasList
from .views import AcessoriosCreate
from .views import AcessoriosUpdate
from .views import AcessoriosDelete
from .views import AcessoriosList
from . import views

urlpatterns = [
    path('cadastrar/carretas/', CarretasCreate.as_view(), name='cadastrar-carretas'),

    path('editar/cadastros/carretas/<int:pk>', CarretasUpdate.as_view(), name='editar-cadastros-carretas'),

    path('excluir/cadastros/carretas/<int:pk>', CarretasDelete.as_view(), name='excluir-cadastros-carretas'),

    path('listar/cadastros/carretas/', CarretasList.as_view(), name='listar-cadastros-carretas'),

    path('cadastrar/acessorios/', AcessoriosCreate.as_view(), name='cadastrar-acessorios'),

    path('editar/cadastros/acessorios/<int:pk>', AcessoriosUpdate.as_view(), name='editar-cadastros-acessorios'),

    path('excluir/cadastros/acessorios/<int:pk>', AcessoriosDelete.as_view(), name='excluir-cadastros-acessorios'),

    path('listar/cadastros/acessorios/', AcessoriosList.as_view(), name='listar-cadastros-acessorios'),

    path('carreta/<int:carreta_id>/acessorios/', views.acessorios_carreta, name='acessorios-cadastros-carretas'),

]

backup/carretas/models.py
from django.db import models


# Create your models here.

class Carretas(models.Model):
    frota = models.CharField(max_length=150, verbose_name="Frota")
    placa = models.CharField(max_length=150, unique=True, verbose_name="Placa")
    motorista = models.CharField(max_length=250, verbose_name="Motorista padrão")
    renavam = models.CharField(max_length=250, verbose_name="Renavam")

    GENDER_CHOICES = (
        ('A', '2024/2024'),
        ('B', '2023/2024'),
        ('C', '2022/2023'),
        ('D', '2021/2022'),
        ('E', '2020/2021'),
        ('F', '2019/2020'),
        ('G', '2018/2019'),
        ('H', '2017/2018'),
        ('I', '2016/2017'),
        ('J', '2015/2016'),
        ('K', '2014/2015'),
        ('L', '2013/2014'),
        ('M', '2012/2013'),
        ('N', '2011/2012'),
        ('O', '2010/2011'),
        ('P', '2009/2010'),
        ('Q', '2008/2009'),
        ('R', '2007/2008'),
        ('S', '2006/2007'),
        ('T', '2005/2006'),
        ('U', '2004/2005'),
    )
    anomod = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Ano / Modelo")

    GENDER_CHOICES = (
        ('A', 'Amarela'),
        ('B', 'Azul'),
        ('C', 'Branca'),
        ('D', 'Cinza'),
        ('E', 'Prata'),
        ('F', 'Preta'),
        ('G', 'Vermelho'),
    )
    cor = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Cor")
    chassi = models.CharField(max_length=150, verbose_name="Chassi")

    GENDER_CHOICES = (
        ('A', 'Araucária'),
    )
    crlv = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="CRLV")

    GENDER_CHOICES = (
        ('B', 'BIASI'),
        ('F', 'FACCHINI'),
        ('G', 'GOTTI'),
        ('K', 'KRONORTE'),
        ('M', 'METALESP'),
        ('R', 'R/TRIEL'),
        ('S', 'RANDON'),
        ('T', 'RECRUSUL'),
        ('U', 'RHODOSS'),
        ('V', 'RODOTEC'),
        ('W', 'RODOTÉCNICA'),
        ('X', 'RODOTIC'),
        ('Y', 'TRIEL'),
    )
    marca = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Marca")

    GENDER_CHOICES = (
        ('B', 'BITREM DIANTEIRO'),
        ('C', 'BITREM TRASEIRO'),
        ('D', 'QUATRO PATAS'),
        ('E', 'RODOTREM DIANTEIRO'),
        ('F', 'RODOTREM TRASEIRO'),
        ('G', 'VANDERLÉIA'),
    )
    modelo = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Modelo")

    GENDER_CHOICES = (
        ('A', '2'),
        ('B', '3'),
        ('C', '4'),
    )
    eixos = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Eixos")

    GENDER_CHOICES = (
        ('A', '295/80'),
        ('B', 'Single'),
    )
    pneus = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Pneus")

    GENDER_CHOICES = (
        ('M', 'Mecânica'),
        ('P', 'Pneumática'),
    )
    suspensao = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Suspensão")
    altura = models.DecimalField(max_digits=6, decimal_places=3, verbose_name="Altura")
    pbt = models.DecimalField(max_digits=6, decimal_places=3, verbose_name="PBT")
    toneladas = models.DecimalField(max_digits=6, decimal_places=3, verbose_name="Toneladas")
    litros = models.DecimalField(max_digits=6, decimal_places=3, verbose_name="Litros")

    GENDER_CHOICES = (
        ('A', 'A.CARB'),
        ('B', 'ALUM'),
        ('C', 'BASC'),
        ('D', 'INOX'),
        ('E', 'LS'),
        ('F', 'TERM'),
    )
    tipo = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Tipo")

    tara = models.DecimalField(max_digits=6, decimal_places=3, verbose_name="Tara")

    GENDER_CHOICES = (
        ('A', '1°'),
        ('B', '1°, 2°'),
        ('C', '1°, 2°, 3°'),
        ('D', '1°, 2°, 4°'),
        ('E', '1°, 3°'),
    )
    suspensor = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Suspensor eixos")
    bolsa = models.CharField(max_length=150, verbose_name="Bolsa suspensor")

    GENDER_CHOICES = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )
    mola = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Mola pneumática")
    locada = models.CharField(max_length=150, verbose_name="Locada")

    GENDER_CHOICES = (
        ('V', 'VIA DUPLA'),
    )
    transportadora = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Transportadora")

    GENDER_CHOICES = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )
    notafiscal = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Nota fiscal")
    status = models.CharField(max_length=150, verbose_name="Status")

    def __str__(self):
        return f"{self.placa}"


class Acessorios(models.Model):
    carreta = models.ForeignKey('Carretas', on_delete=models.CASCADE, related_name='Acessorios')
    placaacc = models.ForeignKey(Carretas, to_field='placa', on_delete=models.CASCADE, verbose_name="PlacaAcc")

    GENDER_CHOICES = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )
    bottomclaro = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Bottom claro")

    GENDER_CHOICES = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )
    bottomescuro = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Bottom escuro")

    GENDER_CHOICES = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )
    bottomtepar = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Bottom Tepar")

    GENDER_CHOICES = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )
    api = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="API")

    GENDER_CHOICES = (
        ('A', '1T'),
        ('B', '2T'),
        ('C', '2T ISOLADO'),
        ('D', 'Não'),
    )
    descarga = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Enc. Descarga")

    GENDER_CHOICES = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )
    dreno = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Reg. No dreno")

    GENDER_CHOICES = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )
    graudbolt = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Graud bolt Itajaí")

    GENDER_CHOICES = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )
    olhodegato = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Olho de gato")

    GENDER_CHOICES = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )
    mangote = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Mangote")

    GENDER_CHOICES = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )
    macarico = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Maçarico")

    def __str__(self):
        return f"{self.placaacc.placa}"

backup/carretas/templates/lista/acessorios-list.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Listagem dos acessorios</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/acessorios-list.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.7.2/font/bootstrap-icons.min.css">
</head>
<style>
    .header-text {
        font-family: Arial, sans-serif; /* Fonte Arial */
        font-size: 38px; /* Tamanho do texto 25px */
        text-align: center; /* Centralizar texto */
        font-weight: 600;
        color: #F2B72F;
        padding: 0px 20px;
        z-index: 999;
        margin-top: 30px;
        margin-bottom: -50px;
    }
</style>
<body>

    <a href="{% url 'listagens' %}">
        <button class="back-button" onclick="window.history.back();">
            <i class="bi bi-arrow-left-circle-fill"></i>
        </button>
    </a>

    <img class="footer-image" src="{% static 'img/rodapépreto.jpg' %}">
    <img class="image1" src="{% static 'img/linhadocabeçalho.jpg' %}">
    <a href="{% url 'menu' %}">
        <img class="image3" src="{% static 'img/logoVD_FundoEscuro.png' %}">
    </a>


<div class="container">
    <table class="table table-dark table-striped">
        <header class="container header-text">Listagem dos acessorios</header>
        <thead>
        <tr>
            <th class="sticky">PlacaAcc</th>
            <th>Bottom claro</th>
            <th>Bottom escuro</th>
            <th>Bottom Tepar</th>
            <th>API</th>
            <th>Enc. Descarga</th>
            <th>Reg. No dreno</th>
            <th>Graud bolt Itajaí</th>
            <th>Olho de gato</th>
            <th>Mangote</th>
            <th>Maçarico</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        {% for Acessorios in object_list %}
            <tr>
            <td class="sticky cell-frota">{{ acessorios.get_placaacc_display }}</td>
            <td>{{ acessorios.get_bottomclaro_display }}</td>
            <td>{{ acessorios.get_bottomescuro_display }}</td>
            <td>{{ acessorios.get_bottomtepar_display }}</td>
            <td>{{ acessorios.get_api_display }}</td>
            <td>{{ acessorios.get_descarga_display }}</td>
            <td>{{ acessorios.get_dreno_display }}</td>
            <td>{{ acessorios.get_graudbolt_display }}</td>
            <td>{{ acessorios.get_olhodegato_display }}</td>
            <td>{{ acessorios.get_mangote_display }}</td>
            <td>{{ acessorios.get_macarico_display }}</td>
            <td>
                <a href="{% url 'editar-cadastros-acessorios' acessorios.pk %}" class="btn btn-warning btn-sm" title="Editar">Editar</a>
                <a href="{% url 'excluir-cadastros-acessorios' acessorios.pk %}" class="btn btn-warning btn-sm" title="Excluir">Excluir</a>
                <a href="{% url 'acessorios-cadastros-acessorios' acessorios.pk %}" class="btn btn-info btn-sm" title="Acessórios">Acessórios</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td class="sticky cell-id" colspan="27">Nenhum campo registrado</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

backup/carretas/templates/lista/carretas-list.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Listagem das carretas</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/carretas-list.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.7.2/font/bootstrap-icons.min.css">
</head>
<style>
    .header-text {
        font-family: Arial, sans-serif; /* Fonte Arial */
        font-size: 38px; /* Tamanho do texto 25px */
        text-align: center; /* Centralizar texto */
        font-weight: 600;
        color: #F2B72F;
        padding: 0px 20px;
        z-index: 999;
        margin-top: 30px;
        margin-bottom: -50px;
    }
</style>
<body>

    <a href="{% url 'listagens' %}">
        <button class="back-button" onclick="window.history.back();">
            <i class="bi bi-arrow-left-circle-fill"></i>
        </button>
    </a>

    <img class="footer-image" src="{% static 'img/rodapépreto.jpg' %}">
    <img class="image1" src="{% static 'img/linhadocabeçalho.jpg' %}">
    <a href="{% url 'menu' %}">
        <img class="image3" src="{% static 'img/logoVD_FundoEscuro.png' %}">
    </a>


<div class="container">
    <table class="table table-dark table-striped">
        <header class="container header-text">Listagem das carretas</header>
        <thead>
        <tr>
            <th class="sticky">Frota</th>
            <th class="sticky">Placa</th>
            <th>Motorista</th>
            <th>Renavam</th>
            <th>Anomod</th>
            <th>Cor</th>
            <th>Chassi</th>
            <th>Crlv</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Eixos</th>
            <th>Pneus</th>
            <th>Suspensao</th>
            <th>Altura</th>
            <th>Pbt</th>
            <th>Toneladas</th>
            <th>Litros</th>
            <th>Tipo</th>
            <th>Tara</th>
            <th>Suspensor</th>
            <th>Bolsa</th>
            <th>Mola</th>
            <th>Locada</th>
            <th>Transportadora</th>
            <th>Notafiscal</th>
            <th>Status</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        {% for carretas in object_list %}
            <tr>
            <td class="sticky cell-frota">{{ carretas.frota }}</td>
            <td class="sticky cell-placa">{{ carretas.placa }}</td>
            <td>{{ carretas.motorista }}</td>
            <td>{{ carretas.renavam }}</td>
            <td>{{ carretas.get_anomod_display }}</td>
            <td>{{ carretas.get_cor_display }}</td>
            <td>{{ carretas.chassi }}</td>
            <td>{{ carretas.get_crlv_display }}</td>
            <td>{{ carretas.get_marca_display }}</td>
            <td>{{ carretas.get_modelo_display }}</td>
            <td>{{ carretas.get_eixos_display }}</td>
            <td>{{ carretas.get_pneus_display }}</td>
            <td>{{ carretas.get_suspensao_display }}</td>
            <td>{{ carretas.altura }}</td>
            <td>{{ carretas.pbt }}</td>
            <td>{{ carretas.toneladas }}</td>
            <td>{{ carretas.litros }}</td>
            <td>{{ carretas.get_tipo_display }}</td>
            <td>{{ carretas.tara }}</td>
            <td>{{ carretas.get_suspensor_display }}</td>
            <td>{{ carretas.bolsa }}</td>
            <td>{{ carretas.get_mola_display }}</td>
            <td>{{ carretas.locada }}</td>
            <td>{{ carretas.get_transportadora_display }}</td>
            <td>{{ carretas.get_notafiscal_display }}</td>
            <td>{{ carretas.status }}</td>
            <td>
                <a href="{% url 'editar-cadastros-carretas' carretas.pk %}" class="btn btn-warning btn-sm" title="Editar">Editar</a>
                <a href="{% url 'excluir-cadastros-carretas' carretas.pk %}" class="btn btn-warning btn-sm" title="Excluir">Excluir</a>
                <a href="{% url 'acessorios-cadastros-carretas' carretas.pk %}" class="btn btn-info btn-sm" title="Acessórios">Acessórios</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td class="sticky cell-id" colspan="27">Nenhum campo registrado</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>